[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string]$Name,          # 表示名 "Esthe"

    [Parameter(Mandatory)]
    [string]$Slug,          # "esthe"

    [string]$Primary = "#0A1A2F",
    [string]$Accent  = "#D4AF37",
    [string]$Surface = "#FFFFFF",

    [string]$RepoRoot = "$HOME/repo/line-booking"
)

$ErrorActionPreference = "Stop"

$uiRoot     = Join-Path $RepoRoot "booking-ui"
$tplDir     = Join-Path $uiRoot "templates"
$tplPath    = Join-Path $tplDir "$Slug.yaml"
$indexPath  = Join-Path $tplDir "index.json"

if (-not (Test-Path $tplDir)) {
    Write-Host "📁 Create templates dir: $tplDir"
    New-Item -ItemType Directory -Path $tplDir -Force | Out-Null
}

if (Test-Path $tplPath) {
    throw "テンプレート $Slug は既に存在する: $tplPath"
}

$yaml = @"
# Auto-generated by New-BookingTemplate.ps1
name: "$Name"
slug: "$Slug"

brand:
  primary: "$Primary"
  accent: "$Accent"
  surface: "$Surface"

layout:
  hero:
    title: "$Name 予約"
    subtitle: "プレミアム体験をオンラインで簡単予約"
    description: "$Name 用の説明文をここに書く"
    image: "/img/$Slug/hero.webp"
    ctaLabel: "今すぐ予約する"

  sections:
    - type: "features"
      title: "選ばれる理由"
      items:
        - title: "特徴1"
          description: "ここに特徴1の説明を入れる"
        - title: "特徴2"
          description: "ここに特徴2の説明を入れる"

meta:
  tags:
    - "$Slug"
    - "booking"
  note: "必要に応じて編集してください"
"@

Write-Host "📝 Create template yaml: $tplPath"
$yaml | Set-Content -Path $tplPath -Encoding UTF8

# index.json 更新（テンプレ一覧用）
if (Test-Path $indexPath) {
    $json = Get-Content $indexPath -Raw | ConvertFrom-Json
} else {
    $json = @()
}

# 同じ slug があれば上書き、無ければ追加
$json = @(
    $json | Where-Object { $_.slug -ne $Slug }
    [pscustomobject]@{
        name = $Name
        slug = $Slug
    }
)

$json | ConvertTo-Json -Depth 3 | Set-Content -Path $indexPath -Encoding UTF8

Write-Host "✅ 新規テンプレ $Slug 生成完了"
Write-Host "   - YAML : $tplPath"
Write-Host "   - index: $indexPath"
Write-Host ""
Write-Host "次のURLで確認 (stg 例):"
Write-Host "  https://85283f05.booking-ui-4pk.pages.dev/?template=$Slug"
