name: deploy / api (push, stable)

on:
  push:
    branches: [ master, main ]
    paths:
      - "api/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Wrangler (pinned)
        run: npm i -g wrangler@3.80.0

      - name: Show tree (debug)
        run: |
          echo "pwd=$(pwd)"
          ls -la
          ls -la api

      - name: Whoami (token check)
        working-directory: api
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: wrangler whoami

      - name: Deploy (verbose)
        working-directory: api
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: wrangler deploy --verbose
