name: deploy / api (push, stable)

on:
  push:
    branches: [ master ]
    paths:
      - "api/**"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (for debug cmds)
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # --- デバッグ: トークンで見えるかを事前チェック（失敗したら原因が明確になります）
      - name: Whoami (token check)
        run: |
          npx wrangler@4 whoami
          npx wrangler@4 kv namespace list | head -n 50 || true
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      # --- 本番デプロイ
      - name: Deploy with Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: api
          command: deploy
