name: deploy / api (push, stable)

on:
  push:
    paths:
      - 'api/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # デバッグ: 位置と設定を出す
      - name: Show files + wrangler.toml
        run: |
          ls -la
          echo "--- api ---"
          ls -la api || true
          echo "--- wrangler.toml (masked id) ---"
          sed -e 's/\(id = "\).*\("\)/\1***\2/' api/wrangler.toml || true

      # まずはドライランで詳細ログを**必ず表示**（失敗しても続行）
      - name: Wrangler dry-run (verbose)
        working-directory: api
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: npx -y wrangler@4.40.2 deploy --dry-run --verbose || true

      # 本番デプロイ（ここで失敗したらログ全文が出る）
      - name: Deploy (CLI verbose)
        working-directory: api
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: npx -y wrangler@4.40.2 deploy --verbose
