name: deploy / api (push, verbose)

on:
  push:
    branches: [ master, main ]
    paths:
      - "api/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Show tree (debug)
        run: |
          echo "pwd=$(pwd)"
          ls -la
          ls -la api

      - name: Wrangler version
        working-directory: api
        run: npx --yes wrangler@3 --version

      - name: Wrangler whoami (auth check)
        working-directory: api
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: npx --yes wrangler@3 whoami

      - name: Deploy (verbose)
        working-directory: api
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: npx --yes wrangler@3 deploy --verbose
