name: deploy / api (push, stable)

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Show files + wrangler.toml
        run: |
          ls -la
          echo "--- wrangler.toml (masked id) ---"
          sed -n '1,200p' api/wrangler.toml | sed -E 's/(id = ")([^"]+)(")/\1***\3/g'
          echo "--- end ---"

      - name: Wrangler dry-run (staging)
        working-directory: api
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          WRANGLER_LOG: debug
        run: npx -y wrangler@4.40.2 deploy --dry-run --env staging

      - name: Deploy (CLI, staging)
        working-directory: api
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          WRANGLER_LOG: debug
        run: npx -y wrangler@4.40.2 deploy --env staging

      - name: Dump wrangler logs (on fail)
        if: failure()
        run: |
          LOG=$(ls -t ~/.config/.wrangler/logs/wrangler-*.log 2>/dev/null | head -n1 || true)
          if [ -f "$LOG" ]; then
            echo "===== Wrangler internal log ====="
            sed -n '1,400p' "$LOG"
            echo "===== end ====="
          else
            echo "No wrangler log file found."
          fi
