name: Deploy Workers

on:
  push:
    branches: [ main ]    # main 直pushで staging に自動デプロイ
  workflow_dispatch:
    inputs:
      env:
        description: "Deploy environment"
        required: true
        default: "prod"
        type: choice
        options: [ "staging", "prod" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CF_API_TOKEN:  ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: npm i -g wrangler@4

      # Secrets を環境変数として渡す（lineReply 用）
      - name: Set secrets
        run: |
          wrangler secret put LINE_CHANNEL_ACCESS_TOKEN --env=staging <<< "${{ secrets.LINE_CHANNEL_ACCESS_TOKEN_STG }}"
          wrangler secret put LINE_CHANNEL_ACCESS_TOKEN --env=prod    <<< "${{ secrets.LINE_CHANNEL_ACCESS_TOKEN_PROD }}"
          wrangler secret put LINE_CHANNEL_SECRET       --env=staging <<< "${{ secrets.LINE_CHANNEL_SECRET_STG }}"
          wrangler secret put LINE_CHANNEL_SECRET       --env=prod    <<< "${{ secrets.LINE_CHANNEL_SECRET_PROD }}"
          wrangler secret put ADMINS                    --env=staging <<< "${{ secrets.ADMINS_STG }}"
          wrangler secret put ADMINS                    --env=prod    <<< "${{ secrets.ADMINS_PROD }}"
          # 任意: Slack 通知
          if [[ -n "${{ secrets.SLACK_WEBHOOK_URL_STG }}" ]]; then wrangler secret put SLACK_WEBHOOK_URL --env=staging <<< "${{ secrets.SLACK_WEBHOOK_URL_STG }}"; fi
          if [[ -n "${{ secrets.SLACK_WEBHOOK_URL_PROD }}" ]]; then wrangler secret put SLACK_WEBHOOK_URL --env=prod    <<< "${{ secrets.SLACK_WEBHOOK_URL_PROD }}"; fi

      - name: Deploy to staging on push
        if: ${{ github.event_name == 'push' }}
        run: wrangler deploy --env=staging

      - name: Deploy to selected env on manual run
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          if [ "${{ inputs.env }}" = "staging" ]; then
            wrangler deploy --env=staging
          else
            wrangler deploy --env=prod
          fi
