name: deploy / api (push, stable)

on:
  push:
    paths:
      - 'api/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (for debug cmds)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 任意：設定確認しやすくする
      - name: Print wrangler.toml (debug)
        run: |
          echo "---- wrangler.toml ----"
          sed -e 's/id = "\(.*\)"/id = "***"/' wrangler.toml || true
          echo "-----------------------"

      - name: Whoami (token check)
        run: |
          npx -y wrangler@4.40.2 whoami || true

      - name: Deploy with Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          wranglerVersion: '4.40.2'
          workingDirectory: 'api'
          command: deploy --verbose
