# …前略…

  - name: Wrangler dry-run (staging)
    working-directory: api
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      WRANGLER_LOG: debug
    run: npx -y wrangler@4.40.2 deploy --dry-run --env staging

  - name: Deploy (CLI, staging)
    working-directory: api   # ★これが無いとルートで実行されて entrypoint が見失われる
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      WRANGLER_LOG: debug
    run: npx -y wrangler@4.40.2 deploy --env staging
