name: deploy / api (push, stable)

on:
  push:
    branches: [ master, main ]
    paths:
      - "api/**"
      - "!api/web/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy with Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}  # ← 作り直したトークン
          # accountId は toml に書いてあるので不要
          workingDirectory: api
          command: deploy
